### PR TITLE
Rename packit-service-worker to packit-worker

### PR DESCRIPTION
**Pull request by mmuzila**

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]
Looks OK to me. I'll play with it next week. Thanks!

**Comment by TomasTomecek** [comment]
The CI failure seems to be pretty relevant:
```
/home/zuul-worker/src/github.com/packit/deployment/playbooks/../openshift/packit-worker.yml.j2 could not be found
```

**Comment by mmuzila** [comment]
> The CI failure seems to be pretty relevant:
> 
> ```
> /home/zuul-worker/src/github.com/packit/deployment/playbooks/../openshift/packit-worker.yml.j2 could not be found
> ```

Hi,
the problem with ^^ was fixed by a2fd9f4.

However there seems to be another problem:
```
 "message": "OCI runtime create failed: container_linux.go:349: starting container process caused \"exec: \\\"/usr/bin/run_worker.sh\\\": stat /usr/bin/run_worker.sh: no such file or directory\": unknown",
```
I haven't found its cause yet.

**Comment by jpopelka** [comment]
[Build rules on Docker Hub](https://hub.docker.com/repository/docker/usercont/packit-worker/builds/edit) were set to build from [Dockerfile](https://github.com/packit/packit-service/blob/master/files/docker/Dockerfile) instead of [Dockerfile.worker](https://github.com/packit/packit-service/blob/master/files/docker/Dockerfile.worker).
I fixed it and it's currently building new images.
I'll retrigger the tests once they're done.

**Comment by jpopelka** [comment]
recheck

**Comment by TomasTomecek** [comment]
wow, awesome, green!!

**Comment by TomasTomecek** [comment]
@lachmanfrantisek  you're doing the next prod deployment, FYI this PR will require running `make deploy`

**Comment by jpopelka** [comment]
I'm going to try this locally and then (if it's ok) on stage so I think I'd just go and do prod (if stg is ok) as well.

**Comment by jpopelka** [comment]
Both, `stg` and `prod` have been redeployed with the content of this PR.

**Comment by TomasTomecek** [comment]
:O

Kudos!

**Pull request merged**
