### PR TITLE
Expose Sentry related env var in dashboard pod

### PR DESCRIPTION
**Pull request by lbarcziova**
Related to packit/dashboard#410

### CODE REVIEW

**Comment by lbarcziova** [comment]
I see the PR actually requires 2 env vars, I will have a look into the SENTRY_AUTH_TOKEN.

**Review by mfocko — COMMENTED** [review]
Why isn't DSN enough? :eyes:

**Comment by Venefilyn** [comment]
> Why isn't DSN enough? 👀

@mfocko `SENTRY_AUTH_TOKEN` is to provide sourcemaps to Sentry so that it can decipher production builds, as they are minimized

**Comment by mfocko** [comment]
Correct me if I'm wrong, but based on the docs:

- https://www.npmjs.com/package/@sentry/vite-plugin#authtoken
- https://docs.sentry.io/platforms/javascript/guides/gcp-functions/sourcemaps/uploading/vite/#configuration

I understand that this token needs to be present during the **build**, not **while** deployed, so this is something that should be exposed in the dashboard repo **and** for the GH Action (that actually builds the images).

Based on the docs from the first link, I have a feeling that it should work correctly by matching the commit SHA to the image.

(Based on the discussion with @lbarcziova)

**Comment by Venefilyn** [comment]
> I understand that this token needs to be present during the build, not while deployed

Correct, should only be needed during build

**Comment by lbarcziova** [comment]
thanks @Venefilyn for confirmation! Then I updated this PR only adding the VITE_SENTRY_DSN and the SENTRY_AUTH_TOKEN will be added in the dashboard repo.

**Review by mfocko — APPROVED** [review]

**Pull request merged**
