### PR TITLE
[secrets/template/extra-vars.yml] set meaningful postgres_host

### PR DESCRIPTION
**Pull request by jpopelka**
This template is actually used when testing packit-service in Zuul.

### CODE REVIEW

**Comment by jpopelka** [comment]
Merging, I need this for https://github.com/packit/packit-service/pull/805

**Comment by csomh** [comment]
Shouldn't testing update these values with something meaningful, instead of hard-coding values here?

I think it will be confusing to someone at some point that they modify a—what they think is a—template and suddenly break testing.

**Comment by jpopelka** [comment]
@csomh is https://github.com/packit/packit-service/issues/807 what you're suggesting?

**Comment by csomh** [comment]
Yes. Thanks!

**Pull request merged**
