### PR TITLE
[containers/Dockerfile.base] FROM fedora:31 -> fedora:32

### PR DESCRIPTION
**Pull request by jpopelka**
I'm currently building/testing packit-service[-worker] with it.

### CODE REVIEW

**Comment by sakalosj** [comment]
@jpopelka 
it was already configured in 
https://github.com/packit/packit-service/pull/717

but workers were failing so was reverted back in
https://github.com/packit/packit-service/pull/751

so not sure if it will work without additional troubleshooting and fixes

**Comment by jpopelka** [comment]
Thanks

**Comment by jpopelka** [comment]
@sakalosj tests in https://github.com/packit/packit-service/pull/826 are passing so we're free to give this a try. Will you give me your blessing?

**Review by sakalosj — APPROVED** [review]

**Comment by sakalosj** [comment]
> @sakalosj tests in [packit/packit-service#826](https://github.com/packit/packit-service/pull/826) are passing so we're free to give this a try. Will you give me your blessing?

Yes, my son. :)

**Pull request merged**
