### PR TITLE
AWS secrets

### PR DESCRIPTION
**Pull request by jpopelka**
This PR sets variables needed (for p-s) to be able to use AWS SQS & RDS PostgreSQL

* https://github.com/packit/packit-service/pull/800
* https://github.com/packit/packit-service-fedmsg/pull/18
* https://github.com/packit/packit-service-centosmsg/pull/11

### CODE REVIEW

**Comment by csomh** [comment]
What happens if `aws_access_key_id` and `aws_secret_access_key` is not present in `extra-vars`?

**Comment by jpopelka** [comment]
> What happens if `aws_access_key_id` and `aws_secret_access_key` is not present in `extra-vars`?

explodes :boom: 

https://gitlab.cee.redhat.com/user-cont/packit-service/-/merge_requests/101

**Comment by jpopelka** [comment]
Updated with `QUEUE_NAME_PREFIX` being always set.

**Review by csomh — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
