### PR TITLE
Allow github.com/theforeman/foreman-installer to use internal TF

### PR DESCRIPTION
**Pull request by nforro**
Requested by @ekohl.

### CODE REVIEW

**Comment by nforro** [comment]
recheck

**Comment by nforro** [comment]
recheck

**Review by majamassarini — APPROVED** [review]
🙏

**Review by lachmanfrantisek — APPROVED** [review]

**Comment by nforro** [comment]
recheck

**Comment by ekohl** [comment]
I tried to rerun https://github.com/theforeman/foreman-installer/pull/921 but it still doesn't allow RHEL composes. It's unclear to me how I actually get my tests to run.

As an aside: it is also possible to build on RHEL but run the tests upstream on CentOS Stream? For our specific tests we care less that it's really compatible with RHEL and having completely visible logs to all upstream users is important.

**Comment by nforro** [comment]
> I tried to rerun [theforeman/foreman-installer#921](https://github.com/theforeman/foreman-installer/pull/921) but it still doesn't allow RHEL composes. It's unclear to me how I actually get my tests to run.

I've commented on the PR.

> As an aside: it is also possible to build on RHEL but run the tests upstream on CentOS Stream? For our specific tests we care less that it's really compatible with RHEL and having completely visible logs to all upstream users is important.

Yes, I suppose something like this should work (in this case you don't need `use_internal_tf` of course):

```yaml
  - job: tests
    trigger: pull_request
    targets:
      rhel-8-x86_64:
        distros: [centos-stream-8]
      rhel-9-x86_64:
        distros: [centos-stream-9]
```

**Pull request merged**
